version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: feature-voting-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app.db
      - SECRET_KEY=your-secret-key-change-in-production
    volumes:
      - app_data:/app/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  app_data:

networks:
  app-network:
    driver: bridge
